#!/usr/bin/env python3
"""Generate and email a weekly social post pack to adam@saahomes.com."""
import smtplib, os, json
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# Read SMTP creds
with open('/opt/data/.env') as f:
    env = {}
    for line in f:
        line = line.strip()
        if '=' in line and not line.startswith('#'):
            k, v = line.split('=', 1)
            env[k.strip()] = v.strip()

smtp_host = env.get('OUTREACH_SMTP_HOST', 'smtp.gmail.com')
smtp_user = env.get('OUTREACH_SMTP_USER', 'adam@saahomes.com')
smtp_pass = env.get('OUTREACH_SMTP_PASSWORD', '').replace(' ', '')
today = datetime.now().strftime('%B %d, %Y')

body_html = f"""<html>
<body style="font-family: Arial; max-width: 600px; margin:0 auto; padding:20px;">
<h2 style="color:#CFB36E;">📬 Weekly Social Post Pack — {today}</h2>
<p>Weekly content to copy/paste into each platform.</p>
<hr style="border:1px solid #eee;">

<h3>📌 Google Business Profile</h3>
<p style="background:#f5f5f5; padding:12px; border-radius:6px;">
Thinking of buying or selling in Northern Colorado? Schwartz and Associates helps buyers and sellers across 19 communities — from Fort Collins to Niwot. Whether you need market insights, CHFA program guidance, or just want to know what your home is worth, we're here. Contact us at (970) 999-1407 or visit saahomes.com.
</p>

<h3>📘 Facebook</h3>
<p style="background:#f5f5f5; padding:12px; border-radius:6px;">
Happy {today.split(',')[0]} from SAA Homes! 🏔️<br><br>
Whether you're buying your first home, selling to upsize, or exploring Northern Colorado for the first time — Adam and Mandi Schwartz have you covered across all 19 of our local communities.<br><br>
📞 (970) 999-1407<br>
🌐 saahomes.com<br><br>
#SAAHomes #NorthernColorado #FortCollinsRealEstate #LovelandRealEstate #ColoradoRealtor
</p>

<h3>📸 Instagram</h3>
<p style="background:#f5f5f5; padding:12px; border-radius:6px;">
🏡 Your Northern Colorado real estate experts — serving 19 communities from Fort Collins to Niwot.<br><br>
Whether you're buying, selling, or just exploring, Adam and Mandi Schwartz bring local expertise and personalized service.<br><br>
📞 (970) 999-1407<br>
👉 Link in bio: saahomes.com<br><br>
#SAAHomes #NorthernColoradoRealEstate #FortCollinsRealtor #ColoradoLiving #CHFA #HomeBuyingTips
</p>

<h3>🐦 X (Twitter)</h3>
<p style="background:#f5f5f5; padding:12px; border-radius:6px;">
Northern Colorado real estate experts serving 19 communities — Fort Collins to Niwot. Buying, selling, or just curious? We've got you covered. (970) 999-1407 saahomes.com
</p>

<hr style="border:1px solid #eee;">
<p style="color:#888; font-size:12px;">Generated by Hermes Agent | SAA Homes | {today}</p>
</body>
</html>"""

msg = MIMEMultipart('alternative')
msg['Subject'] = f'[Social Post Pack] Weekly content — {today}'
msg['From'] = f'Hermes Agent <{smtp_user}>'
msg['To'] = 'adam@saahomes.com'
msg.attach(MIMEText(body_html, 'html'))

with smtplib.SMTP_SSL(smtp_host, 465) as server:
    server.login(smtp_user, smtp_pass)
    server.send_message(msg)
print(f"✅ Weekly post pack sent to adam@saahomes.com")
